library(shiny)
library(tidyverse)
library(ggplot2)
library(shinydashboard)
library(RColorBrewer)
#library(foreign)
library(leaflet)
#library(magrittr)
library(dplyr)
library(plotly)
library(sf)
library(gganimate)

traffic <- read_csv("data/traffic.csv")
#View(traffic)
counties <- read_csv("data/counties_geo.csv")
county_data <- read_csv("data/counties_data.shp")


#View(counties)
