```{r}
library(tidyverse)
library(dplyr)
library(sf)
library(ggplot2)
```

```{r}
#Source: https://www.census.gov/geographies/mapping-files/time-series/geo/carto-boundary-file.html
counties <- st_read("../data/cb_2018_us_county_20m.shp")
```

```{r}
counties <- counties %>% 
  filter(STATEFP == 47) %>%
  select(c("COUNTYFP", "NAME", "geometry")) %>%
  arrange(NAME)
colnames(counties) <- c("county_code", "county", "geometry")
```


```{r}
#View(counties)
```

```{r}
# ggplot() + 
#   geom_sf(data = counties, size = 3, color = "black", fill = "cyan1") + 
#   ggtitle("TN Counties") + 
#   coord_sf()
```

Pull County List for use in Google API Notebook
```{r}
# county_list <- data_frame(counties$county)
# View(county_list)
```

```{r}
#write_csv(county_list, "county_list.csv")
```

Import County Geographic Centers, and Merge
```{r}
county_centers <- read_csv("../data/county_centers.csv")
View(county_centers)
```

```{r}
county_centers <- county_centers %>% 
  select(-X1) %>%
  arrange(county)
```

```{r}
counties_merge <- inner_join(counties, county_centers, by = "county")
```

```{r}
View(counties_merge)
```

```{r}
#write_csv(counties, "counties_final.csv")
```

```{r}
ggplot(data = counties) +
  geom_sf(color = "black", aes(fill = county_code))
  
```















