```{r}
library(shiny)
library(tidyverse)
library(ggplot2)
library(shinydashboard)
library(RColorBrewer)
library(foreign)
library(leaflet)
library(magrittr)
library(dplyr)
library(fpp2)
library(fable)
library(tsibble)
library(lubridate)
```

```{r}
traffic <- read.dbf("../data/TrfcHistYR.dbf")
```

```{r}
colnames(traffic) <- str_to_lower(colnames(traffic))
traffic$year <- as.numeric(as.character(traffic$year))
traffic <- rename(traffic, long = x, lat = y) %>%
  filter(year >= 2009) %>%
  group_by(station_id) %>% 
  mutate(pct_change = (adjavgdly/lead(adjavgdly) - 1) * 100)
traffic$pct_change <- traffic$pct_change %>% replace(is.na(.), 0)
traffic$pct_change[which(!is.finite(traffic$pct_change))] <- 0
```

```{r}
#Keep roads with all years
keep_roads <- traffic %>%
  group_by(station_id) %>%
  count(station_id) %>%
  filter(n == 10) %>%
  pull(station_id)
#keep_roads <- remove_roads$station_id
#View(keep_roads)
```

```{r}
#Filter traffic by removing rows with station_id not in keep_roads
traffic <- traffic[traffic$station_id %in% keep_roads, ]
#View(traffic)
#expr[expr$cell_type %in% c("hesc", "bj fibroblast"), ]
```







SKIP FOLLOWING SECTION - DEPRECATED PROJECTION FORMULA
```{r}
#write_csv(traffic, "traffic.csv")
```

```{r}
# #Create formula for caluclating projected growth. Start with adding a weighting column, and multiplying to create weighted pct.
# traffic <- traffic %>%
#   mutate(weight = year - 2009,
#          weighted_pct_change = weight * pct_change)
```

```{r}
# #Find the projected growth rate using the weighted pct changes
# traffic_proj_rates <- traffic %>%
#   group_by(station_id) %>%
#   summarise(proj_rate = sum(pct_change) / sum(weight) * 100) %>%
#   mutate(year = 2020)
# #View(traffic_proj_rates)
```

```{r}
# #Merge traffic projected rates to main traffic dataframe
# traffic <- traffic %>%
#   bind_rows(traffic_proj_rates) %>%
#   arrange(station_id, desc(year))
# View(traffic)
```




FIND WEIGHTED AVERAGE OF TRAFFIC CHANGES PER YEAR
```{r}
traffic_growth <- traffic %>%
  group_by(county, year) %>%
  mutate(traffic_factor = adjavgdly / sum(adjavgdly)) %>% 
  mutate(weighted_traffic = pct_change * traffic_factor) %>%
  summarise(sum(weighted_traffic))
colnames(traffic_growth) <- c("county", "year", "traffic_growth_rate")
View(traffic_growth)
```

```{r}
traffic_growth <- traffic %>%
  group_by(county, year) %>%
  summarise(sum(adjavgdly) - sum(lead(adjavgdly))) %>% View() 
    
    
#     traffic_factor = adjavgdly / sum(adjavgdly)) %>% 
#   mutate(weighted_traffic = pct_change * traffic_factor) %>%
#   summarise(sum(weighted_traffic))
# colnames(traffic_growth) <- c("county", "year", "traffic_growth_rate")
# View(traffic_growth)
```

```{r}
#Create annualized growth rate from 2009-2018
traffic_growth_nine_yr <- traffic %>%
  group_by(county, year) %>%
  summarise(total_daily = sum(adjavgdly)) %>% 
  arrange(county, desc(year)) %>%
  mutate(ann_growth_rate = ((total_daily / lead(total_daily, 9L)) ** (1/9) - 1) * 100) %>%
  filter(year == 2018)
View(traffic_growth_nine_yr)
```

```{r}
#Create annualized growth rate from 2015-2018
traffic_growth_three_yr <- traffic %>%
  filter(year >= 2015) %>%
  group_by(county, year) %>%
  summarise(total_daily = sum(adjavgdly)) %>% 
  arrange(county, desc(year)) %>%
  mutate(ann_growth_rate = ((total_daily / lead(total_daily, 3L)) ** (1/3) - 1) * 100) %>%
  filter(year == 2018)
View(traffic_growth_three_yr)
```


MERGE TRAFFIC FORECAST, POPULATION, AND COMMUTER DATA BY COUNTY BY YEAR
```{r}
#import population and commuter data
census_traffic <- read_csv('../data/census_traffic.csv')
```

```{r}
#merge with traffic forecast
forecast_df <- census_traffic %>%
  inner_join(traffic_growth, by = c("county", "year"))
#View(forecast_df)
write_csv(forecast_df, "forecast_df.csv")
```


TESTING FABLE PACKAGE:
```{r}
#convert to tsibble - test one county for now
forecast_ts <-forecast_df %>%
  mutate(year = lubridate::ymd(year, truncated = 2L)) %>%
  filter(county == "Davidson") %>%
  as_tsibble()
```


```{r}
forecast_ts
```

```{r}
yrs <- c(2001, 2002, 2002, 2002, 2003, 2005)
lubridate::ymd(yrs, truncated = 2L)
```


















BEGIN LEAFLET MAP

```{r}
pal <- colorNumeric(
  palette = "Blues",
  domain = davidson_traffic$pct_change)

davidson_map <- leaflet(davidson_traffic) %>%
  setView(-86.822, 36.134, zoom = 10) %>%
  addTiles() %>%
  addCircleMarkers(
    color = ~pal(pct_change),
    stroke = FALSE, fillOpacity = 0.8,
    lng = ~long,lat = ~lat,
    popup = ~paste0(location,
                    "<br/>Average Daily Traffic: ", adjavgdly,
                    "<br/>Percent Change: ", pct_change))
davidson_map
```




```{r}
#leaflet(options = leafletOptions(minZoom = 0, maxZoom = 18))
```





